// auto-generated (tiered, no_bdlop): shared P1 + per-tier P2 {4,8,16,24,32,44,60}
// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(26,30,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(18,76,2^(34.021769))
// 
// Ring
// degree d = 64
// modulus q = 1099511630309, log(q) ~ 40.0
// factors q = q1
// 
// Compression
// D = 10
// gamma = 500822, log(gamma) ~ 18.933938
// 
// Dimensions of secrets
// s1: m1 = 20
// m: l = 0
// s2: m2 = 56
// 
// Size of secrets
// l2(s1) <= alpha = 111.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 4)
// exact euclidean: yes (dimensions: [16], bounds: [109.0])
// approximate infinity: yes (psi: 2261.9929, dimension: 8, bound: 12159.51)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 203161.6, log(stdev1/1.55) = 17.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 12697.6, log(stdev3/1.55) = 13.0
// stdev4 = 812646.4, log(stdev4/1.55) = 19.0
// 
// Repetition rate
// M1 = 2.7968422
// M2 = 2.3902224
// M3 = 1.0128329
// M4 = 1.0384456
// total = 7.0311734
// 
// Security
// MSIS dimension: 18
// MSIS root hermite factor: 1.0043623
// MLWE dimension: 26
// MLWE root hermite factor: 1.0042737
// 
// Proof size
// ~ 18.6445312500000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937]
// bit length of products: [49, 99]
// inverses: [1, -162099428551732]

#include "lazer.h"
static const limb_t _p1_param_q_limbs[] = {1099511630309UL};
static const int_t _p1_param_q = {{(limb_t *)_p1_param_q_limbs, 1, 0}};
static const limb_t _p1_param_qminus1_limbs[] = {1099511630308UL};
static const int_t _p1_param_qminus1 = {{(limb_t *)_p1_param_qminus1_limbs, 1, 0}};
static const limb_t _p1_param_m_limbs[] = {2195414UL};
static const int_t _p1_param_m = {{(limb_t *)_p1_param_m_limbs, 1, 0}};
static const limb_t _p1_param_mby2_limbs[] = {1097707UL};
static const int_t _p1_param_mby2 = {{(limb_t *)_p1_param_mby2_limbs, 1, 0}};
static const limb_t _p1_param_gamma_limbs[] = {500822UL};
static const int_t _p1_param_gamma = {{(limb_t *)_p1_param_gamma_limbs, 1, 0}};
static const limb_t _p1_param_gammaby2_limbs[] = {250411UL};
static const int_t _p1_param_gammaby2 = {{(limb_t *)_p1_param_gammaby2_limbs, 1, 0}};
static const limb_t _p1_param_pow2D_limbs[] = {1024UL};
static const int_t _p1_param_pow2D = {{(limb_t *)_p1_param_pow2D_limbs, 1, 0}};
static const limb_t _p1_param_pow2Dby2_limbs[] = {512UL};
static const int_t _p1_param_pow2Dby2 = {{(limb_t *)_p1_param_pow2Dby2_limbs, 1, 0}};
static const limb_t _p1_param_Bsq_limbs[] = {131552782163851UL, 0UL};
static const int_t _p1_param_Bsq = {{(limb_t *)_p1_param_Bsq_limbs, 2, 0}};
static const limb_t _p1_param_scM1_limbs[] = {16350601325682650072UL, 14699144400122920028UL, 2UL};
static const int_t _p1_param_scM1 = {{(limb_t *)_p1_param_scM1_limbs, 3, 0}};
static const limb_t _p1_param_scM2_limbs[] = {9736178399405647316UL, 7198332651345687342UL, 2UL};
static const int_t _p1_param_scM2 = {{(limb_t *)_p1_param_scM2_limbs, 3, 0}};
static const limb_t _p1_param_scM3_limbs[] = {17564348299038202954UL, 236724717891962193UL, 1UL};
static const int_t _p1_param_scM3 = {{(limb_t *)_p1_param_scM3_limbs, 3, 0}};
static const limb_t _p1_param_scM4_limbs[] = {11745574133803167714UL, 709195877324474612UL, 1UL};
static const int_t _p1_param_scM4 = {{(limb_t *)_p1_param_scM4_limbs, 3, 0}};
static const limb_t _p1_param_stdev1sq_limbs[] = {41274635715UL, 0UL};
static const int_t _p1_param_stdev1sq = {{(limb_t *)_p1_param_stdev1sq_limbs, 2, 0}};
static const limb_t _p1_param_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t _p1_param_stdev2sq = {{(limb_t *)_p1_param_stdev2sq_limbs, 2, 0}};
static const limb_t _p1_param_stdev3sq_limbs[] = {161229046UL, 0UL};
static const int_t _p1_param_stdev3sq = {{(limb_t *)_p1_param_stdev3sq_limbs, 2, 0}};
static const limb_t _p1_param_stdev4sq_limbs[] = {660394171433UL, 0UL};
static const int_t _p1_param_stdev4sq = {{(limb_t *)_p1_param_stdev4sq_limbs, 2, 0}};
static const limb_t _p1_param_inv2_limbs[] = {549755815154UL};
static const int_t _p1_param_inv2 = {{(limb_t *)_p1_param_inv2_limbs, 1, 1}};
static const limb_t _p1_param_inv4_limbs[] = {274877907577UL};
static const int_t _p1_param_inv4 = {{(limb_t *)_p1_param_inv4_limbs, 1, 1}};
static const unsigned int _p1_param_n[1] = {16};
static const limb_t _p1_param_Bz3sqr_limbs[] = {111012260217UL, 0UL};
static const int_t _p1_param_Bz3sqr = {{(limb_t *)_p1_param_Bz3sqr_limbs, 2, 0}};
static const limb_t _p1_param_Bz4_limbs[] = {13002342UL};
static const int_t _p1_param_Bz4 = {{(limb_t *)_p1_param_Bz4_limbs, 1, 0}};
static const limb_t _p1_param_Pmodq_limbs[] = {142306970403UL};
static const int_t _p1_param_Pmodq = {{(limb_t *)_p1_param_Pmodq_limbs, 1, 0}};
static const limb_t _p1_param_l2Bsq0_limbs[] = {11881UL};
static const int_t _p1_param_l2Bsq0 = {{(limb_t *)_p1_param_l2Bsq0_limbs, 1, 0}};
static const limb_t _p1_param_Ppmodq_0_limbs[] = {2596479UL};
static const int_t _p1_param_Ppmodq_0 = {{(limb_t *)_p1_param_Ppmodq_0_limbs, 1, 1}};
static const limb_t _p1_param_Ppmodq_1_limbs[] = {2595583UL};
static const int_t _p1_param_Ppmodq_1 = {{(limb_t *)_p1_param_Ppmodq_1_limbs, 1, 1}};
static const int_srcptr _p1_param_l2Bsq[] = {_p1_param_l2Bsq0};
static const int_srcptr _p1_param_Ppmodq[] = {_p1_param_Ppmodq_0, _p1_param_Ppmodq_1};
static const polyring_t _p1_param_ring = {{_p1_param_q, 64, 41, 6, moduli_d64, 2, _p1_param_Pmodq, _p1_param_Ppmodq, _p1_param_inv2}};
static const dcompress_params_t _p1_param_dcomp = {{ _p1_param_q, _p1_param_qminus1, _p1_param_m, _p1_param_mby2, _p1_param_gamma, _p1_param_gammaby2, _p1_param_pow2D, _p1_param_pow2Dby2, 10, 0, 22 }};
static const abdlop_params_t _p1_param_tbox = {{ _p1_param_ring, _p1_param_dcomp, 21, 56, 0, 12, 18, _p1_param_Bsq, 1, 8, 5, 140, 1, 17, _p1_param_scM1, _p1_param_stdev1sq, 2, 12, _p1_param_scM2, _p1_param_stdev2sq}};
static const abdlop_params_t _p1_param_quad_eval_ = {{ _p1_param_ring, _p1_param_dcomp, 21, 56, 9, 3, 18, _p1_param_Bsq, 1, 8, 5, 140, 1, 17, _p1_param_scM1, _p1_param_stdev1sq, 2, 12, _p1_param_scM2, _p1_param_stdev2sq}};
static const abdlop_params_t _p1_param_quad_many_ = {{ _p1_param_ring, _p1_param_dcomp, 21, 56, 11, 1, 18, _p1_param_Bsq, 1, 8, 5, 140, 1, 17, _p1_param_scM1, _p1_param_stdev1sq, 2, 12, _p1_param_scM2, _p1_param_stdev2sq}};
static const lnp_quad_eval_params_t _p1_param_quad_eval = {{ _p1_param_quad_eval_, _p1_param_quad_many_, 4}};
static const lnp_tbox_params_t _p1_param = {{ _p1_param_tbox, _p1_param_quad_eval, 4, _p1_param_n, 8, 1, 21, 2, 13, _p1_param_scM3, _p1_param_stdev3sq, 2, 19, _p1_param_scM4, _p1_param_stdev4sq, _p1_param_Bz3sqr, _p1_param_Bz4, &_p1_param_l2Bsq[0], _p1_param_inv4, 19092UL }};

static const unsigned int p1_param_Ps[4] = {16, 17, 18, 19};
static const unsigned int p1_param_Es0[16] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const unsigned int *p1_param_Es[1] = { p1_param_Es0, };
static const unsigned int p1_param_Es_nrows[1] = {16};

static const limb_t p1_param_p_limbs[] = {12289UL};
static const int_t p1_param_p = {{(limb_t *)p1_param_p_limbs, 1, 0}};
static const limb_t p1_param_pinv_limbs[] = {461224058446UL};
static const int_t p1_param_pinv = {{(limb_t *)p1_param_pinv_limbs, 1, 1}};
static const unsigned int p1_param_s1_indices[20] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19};
static const lin_params_t p1_param = {{ _p1_param, 64, p1_param_p, p1_param_pinv, 1, p1_param_s1_indices, 20, NULL, 0,  p1_param_Ps, 4, p1_param_Es, p1_param_Es_nrows, NULL, NULL }};

// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(32,32,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(20,112,2^(40.173114))
// 
// Ring
// degree d = 64
// modulus q = 1125899906843221, log(q) ~ 50.0
// factors q = q1
// 
// Compression
// D = 15
// gamma = 16531490, log(gamma) ~ 23.978713
// 
// Dimensions of secrets
// s1: m1 = 48
// m: l = 0
// s2: m2 = 64
// 
// Size of secrets
// l2(s1) <= alpha = 5836.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 16)
// exact euclidean: yes (dimensions: [16, 16], bounds: [109.0, 5833.9289])
// approximate infinity: yes (psi: 3143.8325, dimension: 8, bound: 8958759.4)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 13002342.4, log(stdev1/1.55) = 23.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 406323.2, log(stdev3/1.55) = 18.0
// stdev4 = 832149913.6, log(stdev4/1.55) = 29.0
// 
// Repetition rate
// M1 = 2.3216894
// M2 = 2.707079
// M3 = 1.03536
// M4 = 1.0197215
// total = 6.6355669
// 
// Security
// MSIS dimension: 20
// MSIS root hermite factor: 1.0043793
// MLWE dimension: 32
// MLWE root hermite factor: 1.0043146
// 
// Proof size
// ~ 29.3593750000000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t _p2_param_4_q_limbs[] = {1125899906843221UL};
static const int_t _p2_param_4_q = {{(limb_t *)_p2_param_4_q_limbs, 1, 0}};
static const limb_t _p2_param_4_qminus1_limbs[] = {1125899906843220UL};
static const int_t _p2_param_4_qminus1 = {{(limb_t *)_p2_param_4_qminus1_limbs, 1, 0}};
static const limb_t _p2_param_4_m_limbs[] = {68106378UL};
static const int_t _p2_param_4_m = {{(limb_t *)_p2_param_4_m_limbs, 1, 0}};
static const limb_t _p2_param_4_mby2_limbs[] = {34053189UL};
static const int_t _p2_param_4_mby2 = {{(limb_t *)_p2_param_4_mby2_limbs, 1, 0}};
static const limb_t _p2_param_4_gamma_limbs[] = {16531490UL};
static const int_t _p2_param_4_gamma = {{(limb_t *)_p2_param_4_gamma_limbs, 1, 0}};
static const limb_t _p2_param_4_gammaby2_limbs[] = {8265745UL};
static const int_t _p2_param_4_gammaby2 = {{(limb_t *)_p2_param_4_gammaby2_limbs, 1, 0}};
static const limb_t _p2_param_4_pow2D_limbs[] = {32768UL};
static const int_t _p2_param_4_pow2D = {{(limb_t *)_p2_param_4_pow2D_limbs, 1, 0}};
static const limb_t _p2_param_4_pow2Dby2_limbs[] = {16384UL};
static const int_t _p2_param_4_pow2Dby2 = {{(limb_t *)_p2_param_4_pow2Dby2_limbs, 1, 0}};
static const limb_t _p2_param_4_Bsq_limbs[] = {143158532224272924UL, 0UL};
static const int_t _p2_param_4_Bsq = {{(limb_t *)_p2_param_4_Bsq_limbs, 2, 0}};
static const limb_t _p2_param_4_scM1_limbs[] = {9859465049745963634UL, 5934122506364705697UL, 2UL};
static const int_t _p2_param_4_scM1 = {{(limb_t *)_p2_param_4_scM1_limbs, 3, 0}};
static const limb_t _p2_param_4_scM2_limbs[] = {15002606599518648986UL, 13043305028329312333UL, 2UL};
static const int_t _p2_param_4_scM2 = {{(limb_t *)_p2_param_4_scM2_limbs, 3, 0}};
static const limb_t _p2_param_4_scM3_limbs[] = {7569140089676268920UL, 652277607672955118UL, 1UL};
static const int_t _p2_param_4_scM3 = {{(limb_t *)_p2_param_4_scM3_limbs, 3, 0}};
static const limb_t _p2_param_4_scM4_limbs[] = {1037701719389014861UL, 363797679677738827UL, 1UL};
static const int_t _p2_param_4_scM4 = {{(limb_t *)_p2_param_4_scM4_limbs, 3, 0}};
static const limb_t _p2_param_4_stdev1sq_limbs[] = {169060907886838UL, 0UL};
static const int_t _p2_param_4_stdev1sq = {{(limb_t *)_p2_param_4_stdev1sq_limbs, 2, 0}};
static const limb_t _p2_param_4_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t _p2_param_4_stdev2sq = {{(limb_t *)_p2_param_4_stdev2sq_limbs, 2, 0}};
static const limb_t _p2_param_4_stdev3sq_limbs[] = {165098542858UL, 0UL};
static const int_t _p2_param_4_stdev3sq = {{(limb_t *)_p2_param_4_stdev3sq_limbs, 2, 0}};
static const limb_t _p2_param_4_stdev4sq_limbs[] = {692473478704487465UL, 0UL};
static const int_t _p2_param_4_stdev4sq = {{(limb_t *)_p2_param_4_stdev4sq_limbs, 2, 0}};
static const limb_t _p2_param_4_inv2_limbs[] = {562949953421610UL};
static const int_t _p2_param_4_inv2 = {{(limb_t *)_p2_param_4_inv2_limbs, 1, 1}};
static const limb_t _p2_param_4_inv4_limbs[] = {281474976710805UL};
static const int_t _p2_param_4_inv4 = {{(limb_t *)_p2_param_4_inv4_limbs, 1, 1}};
static const unsigned int _p2_param_4_n[2] = {16, 16};
static const limb_t _p2_param_4_Bz3sqr_limbs[] = {113676554463109UL, 0UL};
static const int_t _p2_param_4_Bz3sqr = {{(limb_t *)_p2_param_4_Bz3sqr_limbs, 2, 0}};
static const limb_t _p2_param_4_Bz4_limbs[] = {13314398617UL};
static const int_t _p2_param_4_Bz4 = {{(limb_t *)_p2_param_4_Bz4_limbs, 1, 0}};
static const limb_t _p2_param_4_Pmodq_limbs[] = {43822168896UL};
static const int_t _p2_param_4_Pmodq = {{(limb_t *)_p2_param_4_Pmodq_limbs, 1, 1}};
static const limb_t _p2_param_4_l2Bsq0_limbs[] = {11881UL};
static const int_t _p2_param_4_l2Bsq0 = {{(limb_t *)_p2_param_4_l2Bsq0_limbs, 1, 0}};
static const limb_t _p2_param_4_l2Bsq1_limbs[] = {34034726UL};
static const int_t _p2_param_4_l2Bsq1 = {{(limb_t *)_p2_param_4_l2Bsq1_limbs, 1, 0}};
static const limb_t _p2_param_4_Ppmodq_0_limbs[] = {18350992UL};
static const int_t _p2_param_4_Ppmodq_0 = {{(limb_t *)_p2_param_4_Ppmodq_0_limbs, 1, 0}};
static const limb_t _p2_param_4_Ppmodq_1_limbs[] = {13344144UL};
static const int_t _p2_param_4_Ppmodq_1 = {{(limb_t *)_p2_param_4_Ppmodq_1_limbs, 1, 0}};
static const limb_t _p2_param_4_Ppmodq_2_limbs[] = {7842192UL};
static const int_t _p2_param_4_Ppmodq_2 = {{(limb_t *)_p2_param_4_Ppmodq_2_limbs, 1, 0}};
static const int_srcptr _p2_param_4_l2Bsq[] = {_p2_param_4_l2Bsq0, _p2_param_4_l2Bsq1};
static const int_srcptr _p2_param_4_Ppmodq[] = {_p2_param_4_Ppmodq_0, _p2_param_4_Ppmodq_1, _p2_param_4_Ppmodq_2};
static const polyring_t _p2_param_4_ring = {{_p2_param_4_q, 64, 51, 6, moduli_d64, 3, _p2_param_4_Pmodq, _p2_param_4_Ppmodq, _p2_param_4_inv2}};
static const dcompress_params_t _p2_param_4_dcomp = {{ _p2_param_4_q, _p2_param_4_qminus1, _p2_param_4_m, _p2_param_4_mby2, _p2_param_4_gamma, _p2_param_4_gammaby2, _p2_param_4_pow2D, _p2_param_4_pow2Dby2, 15, 0, 27 }};
static const abdlop_params_t _p2_param_4_tbox = {{ _p2_param_4_ring, _p2_param_4_dcomp, 50, 64, 0, 12, 20, _p2_param_4_Bsq, 1, 8, 5, 140, 1, 23, _p2_param_4_scM1, _p2_param_4_stdev1sq, 2, 12, _p2_param_4_scM2, _p2_param_4_stdev2sq}};
static const abdlop_params_t _p2_param_4_quad_eval_ = {{ _p2_param_4_ring, _p2_param_4_dcomp, 50, 64, 9, 3, 20, _p2_param_4_Bsq, 1, 8, 5, 140, 1, 23, _p2_param_4_scM1, _p2_param_4_stdev1sq, 2, 12, _p2_param_4_scM2, _p2_param_4_stdev2sq}};
static const abdlop_params_t _p2_param_4_quad_many_ = {{ _p2_param_4_ring, _p2_param_4_dcomp, 50, 64, 11, 1, 20, _p2_param_4_Bsq, 1, 8, 5, 140, 1, 23, _p2_param_4_scM1, _p2_param_4_stdev1sq, 2, 12, _p2_param_4_scM2, _p2_param_4_stdev2sq}};
static const lnp_quad_eval_params_t _p2_param_4_quad_eval = {{ _p2_param_4_quad_eval_, _p2_param_4_quad_many_, 4}};
static const lnp_tbox_params_t _p2_param_4 = {{ _p2_param_4_tbox, _p2_param_4_quad_eval, 16, _p2_param_4_n, 8, 2, 50, 2, 18, _p2_param_4_scM3, _p2_param_4_stdev3sq, 2, 29, _p2_param_4_scM4, _p2_param_4_stdev4sq, _p2_param_4_Bz3sqr, _p2_param_4_Bz4, &_p2_param_4_l2Bsq[0], _p2_param_4_inv4, 30064UL }};

static const unsigned int p2_param_4_Ps[16] = {16, 17, 18, 19, 20, 21, 22, 23, 40, 41, 42, 43, 44, 45, 46, 47};
static const unsigned int p2_param_4_Es0[16] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const unsigned int p2_param_4_Es1[16] = {24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39};
static const unsigned int *p2_param_4_Es[2] = { p2_param_4_Es0, p2_param_4_Es1, };
static const unsigned int p2_param_4_Es_nrows[2] = {16, 16};

static const limb_t p2_param_4_p_limbs[] = {12289UL};
static const int_t p2_param_4_p = {{(limb_t *)p2_param_4_p_limbs, 1, 0}};
static const limb_t p2_param_4_pinv_limbs[] = {305914215066280UL};
static const int_t p2_param_4_pinv = {{(limb_t *)p2_param_4_pinv_limbs, 1, 0}};
static const unsigned int p2_param_4_s1_indices[48] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47};
static const lin_params_t p2_param_4 = {{ _p2_param_4, 64, p2_param_4_p, p2_param_4_pinv, 1, p2_param_4_s1_indices, 48, NULL, 0,  p2_param_4_Ps, 16, p2_param_4_Es, p2_param_4_Es_nrows, NULL, NULL }};

// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(32,32,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(20,116,2^(40.222359))
// 
// Ring
// degree d = 64
// modulus q = 1125899906843221, log(q) ~ 50.0
// factors q = q1
// 
// Compression
// D = 15
// gamma = 16531490, log(gamma) ~ 23.978713
// 
// Dimensions of secrets
// s1: m1 = 52
// m: l = 0
// s2: m2 = 64
// 
// Size of secrets
// l2(s1) <= alpha = 5836.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 20)
// exact euclidean: yes (dimensions: [16, 16], bounds: [109.0, 5833.9289])
// approximate infinity: yes (psi: 2901.9993, dimension: 8, bound: 9705322.7)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 13002342.4, log(stdev1/1.55) = 23.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 406323.2, log(stdev3/1.55) = 18.0
// stdev4 = 832149913.6, log(stdev4/1.55) = 29.0
// 
// Repetition rate
// M1 = 2.3216894
// M2 = 2.707079
// M3 = 1.0353603
// M4 = 1.0231848
// total = 6.658105
// 
// Security
// MSIS dimension: 20
// MSIS root hermite factor: 1.0043901
// MLWE dimension: 32
// MLWE root hermite factor: 1.0043146
// 
// Proof size
// ~ 30.2031250000000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t _p2_param_8_q_limbs[] = {1125899906843221UL};
static const int_t _p2_param_8_q = {{(limb_t *)_p2_param_8_q_limbs, 1, 0}};
static const limb_t _p2_param_8_qminus1_limbs[] = {1125899906843220UL};
static const int_t _p2_param_8_qminus1 = {{(limb_t *)_p2_param_8_qminus1_limbs, 1, 0}};
static const limb_t _p2_param_8_m_limbs[] = {68106378UL};
static const int_t _p2_param_8_m = {{(limb_t *)_p2_param_8_m_limbs, 1, 0}};
static const limb_t _p2_param_8_mby2_limbs[] = {34053189UL};
static const int_t _p2_param_8_mby2 = {{(limb_t *)_p2_param_8_mby2_limbs, 1, 0}};
static const limb_t _p2_param_8_gamma_limbs[] = {16531490UL};
static const int_t _p2_param_8_gamma = {{(limb_t *)_p2_param_8_gamma_limbs, 1, 0}};
static const limb_t _p2_param_8_gammaby2_limbs[] = {8265745UL};
static const int_t _p2_param_8_gammaby2 = {{(limb_t *)_p2_param_8_gammaby2_limbs, 1, 0}};
static const limb_t _p2_param_8_pow2D_limbs[] = {32768UL};
static const int_t _p2_param_8_pow2D = {{(limb_t *)_p2_param_8_pow2D_limbs, 1, 0}};
static const limb_t _p2_param_8_pow2Dby2_limbs[] = {16384UL};
static const int_t _p2_param_8_pow2Dby2 = {{(limb_t *)_p2_param_8_pow2Dby2_limbs, 1, 0}};
static const limb_t _p2_param_8_Bsq_limbs[] = {143158532224272924UL, 0UL};
static const int_t _p2_param_8_Bsq = {{(limb_t *)_p2_param_8_Bsq_limbs, 2, 0}};
static const limb_t _p2_param_8_scM1_limbs[] = {9859465049745963634UL, 5934122506364705697UL, 2UL};
static const int_t _p2_param_8_scM1 = {{(limb_t *)_p2_param_8_scM1_limbs, 3, 0}};
static const limb_t _p2_param_8_scM2_limbs[] = {15002606599518648986UL, 13043305028329312333UL, 2UL};
static const int_t _p2_param_8_scM2 = {{(limb_t *)_p2_param_8_scM2_limbs, 3, 0}};
static const limb_t _p2_param_8_scM3_limbs[] = {6527119378419402388UL, 652282597756408378UL, 1UL};
static const int_t _p2_param_8_scM3 = {{(limb_t *)_p2_param_8_scM3_limbs, 3, 0}};
static const limb_t _p2_param_8_scM4_limbs[] = {4064522344461472521UL, 427683983330559345UL, 1UL};
static const int_t _p2_param_8_scM4 = {{(limb_t *)_p2_param_8_scM4_limbs, 3, 0}};
static const limb_t _p2_param_8_stdev1sq_limbs[] = {169060907886838UL, 0UL};
static const int_t _p2_param_8_stdev1sq = {{(limb_t *)_p2_param_8_stdev1sq_limbs, 2, 0}};
static const limb_t _p2_param_8_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t _p2_param_8_stdev2sq = {{(limb_t *)_p2_param_8_stdev2sq_limbs, 2, 0}};
static const limb_t _p2_param_8_stdev3sq_limbs[] = {165098542858UL, 0UL};
static const int_t _p2_param_8_stdev3sq = {{(limb_t *)_p2_param_8_stdev3sq_limbs, 2, 0}};
static const limb_t _p2_param_8_stdev4sq_limbs[] = {692473478704487465UL, 0UL};
static const int_t _p2_param_8_stdev4sq = {{(limb_t *)_p2_param_8_stdev4sq_limbs, 2, 0}};
static const limb_t _p2_param_8_inv2_limbs[] = {562949953421610UL};
static const int_t _p2_param_8_inv2 = {{(limb_t *)_p2_param_8_inv2_limbs, 1, 1}};
static const limb_t _p2_param_8_inv4_limbs[] = {281474976710805UL};
static const int_t _p2_param_8_inv4 = {{(limb_t *)_p2_param_8_inv4_limbs, 1, 1}};
static const unsigned int _p2_param_8_n[2] = {16, 16};
static const limb_t _p2_param_8_Bz3sqr_limbs[] = {113676554463109UL, 0UL};
static const int_t _p2_param_8_Bz3sqr = {{(limb_t *)_p2_param_8_Bz3sqr_limbs, 2, 0}};
static const limb_t _p2_param_8_Bz4_limbs[] = {13314398617UL};
static const int_t _p2_param_8_Bz4 = {{(limb_t *)_p2_param_8_Bz4_limbs, 1, 0}};
static const limb_t _p2_param_8_Pmodq_limbs[] = {43822168896UL};
static const int_t _p2_param_8_Pmodq = {{(limb_t *)_p2_param_8_Pmodq_limbs, 1, 1}};
static const limb_t _p2_param_8_l2Bsq0_limbs[] = {11881UL};
static const int_t _p2_param_8_l2Bsq0 = {{(limb_t *)_p2_param_8_l2Bsq0_limbs, 1, 0}};
static const limb_t _p2_param_8_l2Bsq1_limbs[] = {34034726UL};
static const int_t _p2_param_8_l2Bsq1 = {{(limb_t *)_p2_param_8_l2Bsq1_limbs, 1, 0}};
static const limb_t _p2_param_8_Ppmodq_0_limbs[] = {18350992UL};
static const int_t _p2_param_8_Ppmodq_0 = {{(limb_t *)_p2_param_8_Ppmodq_0_limbs, 1, 0}};
static const limb_t _p2_param_8_Ppmodq_1_limbs[] = {13344144UL};
static const int_t _p2_param_8_Ppmodq_1 = {{(limb_t *)_p2_param_8_Ppmodq_1_limbs, 1, 0}};
static const limb_t _p2_param_8_Ppmodq_2_limbs[] = {7842192UL};
static const int_t _p2_param_8_Ppmodq_2 = {{(limb_t *)_p2_param_8_Ppmodq_2_limbs, 1, 0}};
static const int_srcptr _p2_param_8_l2Bsq[] = {_p2_param_8_l2Bsq0, _p2_param_8_l2Bsq1};
static const int_srcptr _p2_param_8_Ppmodq[] = {_p2_param_8_Ppmodq_0, _p2_param_8_Ppmodq_1, _p2_param_8_Ppmodq_2};
static const polyring_t _p2_param_8_ring = {{_p2_param_8_q, 64, 51, 6, moduli_d64, 3, _p2_param_8_Pmodq, _p2_param_8_Ppmodq, _p2_param_8_inv2}};
static const dcompress_params_t _p2_param_8_dcomp = {{ _p2_param_8_q, _p2_param_8_qminus1, _p2_param_8_m, _p2_param_8_mby2, _p2_param_8_gamma, _p2_param_8_gammaby2, _p2_param_8_pow2D, _p2_param_8_pow2Dby2, 15, 0, 27 }};
static const abdlop_params_t _p2_param_8_tbox = {{ _p2_param_8_ring, _p2_param_8_dcomp, 54, 64, 0, 12, 20, _p2_param_8_Bsq, 1, 8, 5, 140, 1, 23, _p2_param_8_scM1, _p2_param_8_stdev1sq, 2, 12, _p2_param_8_scM2, _p2_param_8_stdev2sq}};
static const abdlop_params_t _p2_param_8_quad_eval_ = {{ _p2_param_8_ring, _p2_param_8_dcomp, 54, 64, 9, 3, 20, _p2_param_8_Bsq, 1, 8, 5, 140, 1, 23, _p2_param_8_scM1, _p2_param_8_stdev1sq, 2, 12, _p2_param_8_scM2, _p2_param_8_stdev2sq}};
static const abdlop_params_t _p2_param_8_quad_many_ = {{ _p2_param_8_ring, _p2_param_8_dcomp, 54, 64, 11, 1, 20, _p2_param_8_Bsq, 1, 8, 5, 140, 1, 23, _p2_param_8_scM1, _p2_param_8_stdev1sq, 2, 12, _p2_param_8_scM2, _p2_param_8_stdev2sq}};
static const lnp_quad_eval_params_t _p2_param_8_quad_eval = {{ _p2_param_8_quad_eval_, _p2_param_8_quad_many_, 4}};
static const lnp_tbox_params_t _p2_param_8 = {{ _p2_param_8_tbox, _p2_param_8_quad_eval, 20, _p2_param_8_n, 8, 2, 54, 2, 18, _p2_param_8_scM3, _p2_param_8_stdev3sq, 2, 29, _p2_param_8_scM4, _p2_param_8_stdev4sq, _p2_param_8_Bz3sqr, _p2_param_8_Bz4, &_p2_param_8_l2Bsq[0], _p2_param_8_inv4, 30928UL }};

static const unsigned int p2_param_8_Ps[20] = {16, 17, 18, 19, 20, 21, 22, 23, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51};
static const unsigned int p2_param_8_Es0[16] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const unsigned int p2_param_8_Es1[16] = {24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39};
static const unsigned int *p2_param_8_Es[2] = { p2_param_8_Es0, p2_param_8_Es1, };
static const unsigned int p2_param_8_Es_nrows[2] = {16, 16};

static const limb_t p2_param_8_p_limbs[] = {12289UL};
static const int_t p2_param_8_p = {{(limb_t *)p2_param_8_p_limbs, 1, 0}};
static const limb_t p2_param_8_pinv_limbs[] = {305914215066280UL};
static const int_t p2_param_8_pinv = {{(limb_t *)p2_param_8_pinv_limbs, 1, 0}};
static const unsigned int p2_param_8_s1_indices[52] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51};
static const lin_params_t p2_param_8 = {{ _p2_param_8, 64, p2_param_8_p, p2_param_8_pinv, 1, p2_param_8_s1_indices, 52, NULL, 0,  p2_param_8_Ps, 20, p2_param_8_Es, p2_param_8_Es_nrows, NULL, NULL }};

// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(32,32,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(20,124,2^(40.253753))
// 
// Ring
// degree d = 64
// modulus q = 1125899906843533, log(q) ~ 50.0
// factors q = q1
// 
// Compression
// D = 14
// gamma = 7092726, log(gamma) ~ 22.757909
// 
// Dimensions of secrets
// s1: m1 = 60
// m: l = 0
// s2: m2 = 64
// 
// Size of secrets
// l2(s1) <= alpha = 5836.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 28)
// exact euclidean: yes (dimensions: [16, 16], bounds: [109.0, 5833.9289])
// approximate infinity: yes (psi: 2515.066, dimension: 8, bound: 11198449.0)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 13002342.4, log(stdev1/1.55) = 23.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 406323.2, log(stdev3/1.55) = 18.0
// stdev4 = 832149913.6, log(stdev4/1.55) = 29.0
// 
// Repetition rate
// M1 = 2.3216894
// M2 = 2.707079
// M3 = 1.0353609
// M4 = 1.0309853
// total = 6.7088682
// 
// Security
// MSIS dimension: 20
// MSIS root hermite factor: 1.0043969
// MLWE dimension: 32
// MLWE root hermite factor: 1.0043146
// 
// Proof size
// ~ 32.0468750000000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t _p2_param_16_q_limbs[] = {1125899906843533UL};
static const int_t _p2_param_16_q = {{(limb_t *)_p2_param_16_q_limbs, 1, 0}};
static const limb_t _p2_param_16_qminus1_limbs[] = {1125899906843532UL};
static const int_t _p2_param_16_qminus1 = {{(limb_t *)_p2_param_16_qminus1_limbs, 1, 0}};
static const limb_t _p2_param_16_m_limbs[] = {158740082UL};
static const int_t _p2_param_16_m = {{(limb_t *)_p2_param_16_m_limbs, 1, 0}};
static const limb_t _p2_param_16_mby2_limbs[] = {79370041UL};
static const int_t _p2_param_16_mby2 = {{(limb_t *)_p2_param_16_mby2_limbs, 1, 0}};
static const limb_t _p2_param_16_gamma_limbs[] = {7092726UL};
static const int_t _p2_param_16_gamma = {{(limb_t *)_p2_param_16_gamma_limbs, 1, 0}};
static const limb_t _p2_param_16_gammaby2_limbs[] = {3546363UL};
static const int_t _p2_param_16_gammaby2 = {{(limb_t *)_p2_param_16_gammaby2_limbs, 1, 0}};
static const limb_t _p2_param_16_pow2D_limbs[] = {16384UL};
static const int_t _p2_param_16_pow2D = {{(limb_t *)_p2_param_16_pow2D_limbs, 1, 0}};
static const limb_t _p2_param_16_pow2Dby2_limbs[] = {8192UL};
static const int_t _p2_param_16_pow2Dby2 = {{(limb_t *)_p2_param_16_pow2Dby2_limbs, 1, 0}};
static const limb_t _p2_param_16_Bsq_limbs[] = {28387260565861720UL, 0UL};
static const int_t _p2_param_16_Bsq = {{(limb_t *)_p2_param_16_Bsq_limbs, 2, 0}};
static const limb_t _p2_param_16_scM1_limbs[] = {9859465049745963634UL, 5934122506364705697UL, 2UL};
static const int_t _p2_param_16_scM1 = {{(limb_t *)_p2_param_16_scM1_limbs, 3, 0}};
static const limb_t _p2_param_16_scM2_limbs[] = {15002606599518648986UL, 13043305028329312333UL, 2UL};
static const int_t _p2_param_16_scM2 = {{(limb_t *)_p2_param_16_scM2_limbs, 3, 0}};
static const limb_t _p2_param_16_scM3_limbs[] = {3917818886891532179UL, 652292577927226240UL, 1UL};
static const int_t _p2_param_16_scM3 = {{(limb_t *)_p2_param_16_scM3_limbs, 3, 0}};
static const limb_t _p2_param_16_scM4_limbs[] = {15281807313287836435UL, 571577775297315320UL, 1UL};
static const int_t _p2_param_16_scM4 = {{(limb_t *)_p2_param_16_scM4_limbs, 3, 0}};
static const limb_t _p2_param_16_stdev1sq_limbs[] = {169060907886838UL, 0UL};
static const int_t _p2_param_16_stdev1sq = {{(limb_t *)_p2_param_16_stdev1sq_limbs, 2, 0}};
static const limb_t _p2_param_16_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t _p2_param_16_stdev2sq = {{(limb_t *)_p2_param_16_stdev2sq_limbs, 2, 0}};
static const limb_t _p2_param_16_stdev3sq_limbs[] = {165098542858UL, 0UL};
static const int_t _p2_param_16_stdev3sq = {{(limb_t *)_p2_param_16_stdev3sq_limbs, 2, 0}};
static const limb_t _p2_param_16_stdev4sq_limbs[] = {692473478704487465UL, 0UL};
static const int_t _p2_param_16_stdev4sq = {{(limb_t *)_p2_param_16_stdev4sq_limbs, 2, 0}};
static const limb_t _p2_param_16_inv2_limbs[] = {562949953421766UL};
static const int_t _p2_param_16_inv2 = {{(limb_t *)_p2_param_16_inv2_limbs, 1, 1}};
static const limb_t _p2_param_16_inv4_limbs[] = {281474976710883UL};
static const int_t _p2_param_16_inv4 = {{(limb_t *)_p2_param_16_inv4_limbs, 1, 1}};
static const unsigned int _p2_param_16_n[2] = {16, 16};
static const limb_t _p2_param_16_Bz3sqr_limbs[] = {113676554463109UL, 0UL};
static const int_t _p2_param_16_Bz3sqr = {{(limb_t *)_p2_param_16_Bz3sqr_limbs, 2, 0}};
static const limb_t _p2_param_16_Bz4_limbs[] = {13314398617UL};
static const int_t _p2_param_16_Bz4 = {{(limb_t *)_p2_param_16_Bz4_limbs, 1, 0}};
static const limb_t _p2_param_16_Pmodq_limbs[] = {57284280000UL};
static const int_t _p2_param_16_Pmodq = {{(limb_t *)_p2_param_16_Pmodq_limbs, 1, 1}};
static const limb_t _p2_param_16_l2Bsq0_limbs[] = {11881UL};
static const int_t _p2_param_16_l2Bsq0 = {{(limb_t *)_p2_param_16_l2Bsq0_limbs, 1, 0}};
static const limb_t _p2_param_16_l2Bsq1_limbs[] = {34034726UL};
static const int_t _p2_param_16_l2Bsq1 = {{(limb_t *)_p2_param_16_l2Bsq1_limbs, 1, 0}};
static const limb_t _p2_param_16_Ppmodq_0_limbs[] = {21216400UL};
static const int_t _p2_param_16_Ppmodq_0 = {{(limb_t *)_p2_param_16_Ppmodq_0_limbs, 1, 0}};
static const limb_t _p2_param_16_Ppmodq_1_limbs[] = {15930000UL};
static const int_t _p2_param_16_Ppmodq_1 = {{(limb_t *)_p2_param_16_Ppmodq_1_limbs, 1, 0}};
static const limb_t _p2_param_16_Ppmodq_2_limbs[] = {9709200UL};
static const int_t _p2_param_16_Ppmodq_2 = {{(limb_t *)_p2_param_16_Ppmodq_2_limbs, 1, 0}};
static const int_srcptr _p2_param_16_l2Bsq[] = {_p2_param_16_l2Bsq0, _p2_param_16_l2Bsq1};
static const int_srcptr _p2_param_16_Ppmodq[] = {_p2_param_16_Ppmodq_0, _p2_param_16_Ppmodq_1, _p2_param_16_Ppmodq_2};
static const polyring_t _p2_param_16_ring = {{_p2_param_16_q, 64, 51, 6, moduli_d64, 3, _p2_param_16_Pmodq, _p2_param_16_Ppmodq, _p2_param_16_inv2}};
static const dcompress_params_t _p2_param_16_dcomp = {{ _p2_param_16_q, _p2_param_16_qminus1, _p2_param_16_m, _p2_param_16_mby2, _p2_param_16_gamma, _p2_param_16_gammaby2, _p2_param_16_pow2D, _p2_param_16_pow2Dby2, 14, 0, 28 }};
static const abdlop_params_t _p2_param_16_tbox = {{ _p2_param_16_ring, _p2_param_16_dcomp, 62, 64, 0, 12, 20, _p2_param_16_Bsq, 1, 8, 5, 140, 1, 23, _p2_param_16_scM1, _p2_param_16_stdev1sq, 2, 12, _p2_param_16_scM2, _p2_param_16_stdev2sq}};
static const abdlop_params_t _p2_param_16_quad_eval_ = {{ _p2_param_16_ring, _p2_param_16_dcomp, 62, 64, 9, 3, 20, _p2_param_16_Bsq, 1, 8, 5, 140, 1, 23, _p2_param_16_scM1, _p2_param_16_stdev1sq, 2, 12, _p2_param_16_scM2, _p2_param_16_stdev2sq}};
static const abdlop_params_t _p2_param_16_quad_many_ = {{ _p2_param_16_ring, _p2_param_16_dcomp, 62, 64, 11, 1, 20, _p2_param_16_Bsq, 1, 8, 5, 140, 1, 23, _p2_param_16_scM1, _p2_param_16_stdev1sq, 2, 12, _p2_param_16_scM2, _p2_param_16_stdev2sq}};
static const lnp_quad_eval_params_t _p2_param_16_quad_eval = {{ _p2_param_16_quad_eval_, _p2_param_16_quad_many_, 4}};
static const lnp_tbox_params_t _p2_param_16 = {{ _p2_param_16_tbox, _p2_param_16_quad_eval, 28, _p2_param_16_n, 8, 2, 62, 2, 18, _p2_param_16_scM3, _p2_param_16_stdev3sq, 2, 29, _p2_param_16_scM4, _p2_param_16_stdev4sq, _p2_param_16_Bz3sqr, _p2_param_16_Bz4, &_p2_param_16_l2Bsq[0], _p2_param_16_inv4, 32816UL }};

static const unsigned int p2_param_16_Ps[28] = {16, 17, 18, 19, 20, 21, 22, 23, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59};
static const unsigned int p2_param_16_Es0[16] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const unsigned int p2_param_16_Es1[16] = {24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39};
static const unsigned int *p2_param_16_Es[2] = { p2_param_16_Es0, p2_param_16_Es1, };
static const unsigned int p2_param_16_Es_nrows[2] = {16, 16};

static const limb_t p2_param_16_p_limbs[] = {12289UL};
static const int_t p2_param_16_p = {{(limb_t *)p2_param_16_p_limbs, 1, 0}};
static const limb_t p2_param_16_pinv_limbs[] = {334499191137256UL};
static const int_t p2_param_16_pinv = {{(limb_t *)p2_param_16_pinv_limbs, 1, 0}};
static const unsigned int p2_param_16_s1_indices[60] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59};
static const lin_params_t p2_param_16 = {{ _p2_param_16, 64, p2_param_16_p, p2_param_16_pinv, 1, p2_param_16_s1_indices, 60, NULL, 0,  p2_param_16_Ps, 28, p2_param_16_Es, p2_param_16_Es_nrows, NULL, NULL }};

// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(32,33,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(21,133,2^(40.924567))
// 
// Ring
// degree d = 64
// modulus q = 1125899906843189, log(q) ~ 50.0
// factors q = q1
// 
// Compression
// D = 17
// gamma = 57944746, log(gamma) ~ 25.788175
// 
// Dimensions of secrets
// s1: m1 = 68
// m: l = 0
// s2: m2 = 65
// 
// Size of secrets
// l2(s1) <= alpha = 5836.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 36)
// exact euclidean: yes (dimensions: [16, 16], bounds: [109.0, 5833.9289])
// approximate infinity: yes (psi: 2219.1759, dimension: 8, bound: 12691576.0)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 13002342.4, log(stdev1/1.55) = 23.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 406323.2, log(stdev3/1.55) = 18.0
// stdev4 = 832149913.6, log(stdev4/1.55) = 29.0
// 
// Repetition rate
// M1 = 2.3216894
// M2 = 2.7495318
// M3 = 1.0353614
// M4 = 1.039973
// total = 6.8734837
// 
// Security
// MSIS dimension: 21
// MSIS root hermite factor: 1.0043282
// MLWE dimension: 32
// MLWE root hermite factor: 1.0043146
// 
// Proof size
// ~ 33.5488281250000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t _p2_param_24_q_limbs[] = {1125899906843189UL};
static const int_t _p2_param_24_q = {{(limb_t *)_p2_param_24_q_limbs, 1, 0}};
static const limb_t _p2_param_24_qminus1_limbs[] = {1125899906843188UL};
static const int_t _p2_param_24_qminus1 = {{(limb_t *)_p2_param_24_qminus1_limbs, 1, 0}};
static const limb_t _p2_param_24_m_limbs[] = {19430578UL};
static const int_t _p2_param_24_m = {{(limb_t *)_p2_param_24_m_limbs, 1, 0}};
static const limb_t _p2_param_24_mby2_limbs[] = {9715289UL};
static const int_t _p2_param_24_mby2 = {{(limb_t *)_p2_param_24_mby2_limbs, 1, 0}};
static const limb_t _p2_param_24_gamma_limbs[] = {57944746UL};
static const int_t _p2_param_24_gamma = {{(limb_t *)_p2_param_24_gamma_limbs, 1, 0}};
static const limb_t _p2_param_24_gammaby2_limbs[] = {28972373UL};
static const int_t _p2_param_24_gammaby2 = {{(limb_t *)_p2_param_24_gammaby2_limbs, 1, 0}};
static const limb_t _p2_param_24_pow2D_limbs[] = {131072UL};
static const int_t _p2_param_24_pow2D = {{(limb_t *)_p2_param_24_pow2D_limbs, 1, 0}};
static const limb_t _p2_param_24_pow2Dby2_limbs[] = {65536UL};
static const int_t _p2_param_24_pow2Dby2 = {{(limb_t *)_p2_param_24_pow2Dby2_limbs, 1, 0}};
static const limb_t _p2_param_24_Bsq_limbs[] = {1957442644901174549UL, 0UL};
static const int_t _p2_param_24_Bsq = {{(limb_t *)_p2_param_24_Bsq_limbs, 2, 0}};
static const limb_t _p2_param_24_scM1_limbs[] = {9859465049745963634UL, 5934122506364705697UL, 2UL};
static const int_t _p2_param_24_scM1 = {{(limb_t *)_p2_param_24_scM1_limbs, 3, 0}};
static const limb_t _p2_param_24_scM2_limbs[] = {14165351592000519905UL, 13826422118645399154UL, 2UL};
static const int_t _p2_param_24_scM2 = {{(limb_t *)_p2_param_24_scM2_limbs, 3, 0}};
static const limb_t _p2_param_24_scM3_limbs[] = {17904382677136852103UL, 652302558103259226UL, 1UL};
static const int_t _p2_param_24_scM3 = {{(limb_t *)_p2_param_24_scM3_limbs, 3, 0}};
static const limb_t _p2_param_24_scM4_limbs[] = {2084315199777967655UL, 737371585836722884UL, 1UL};
static const int_t _p2_param_24_scM4 = {{(limb_t *)_p2_param_24_scM4_limbs, 3, 0}};
static const limb_t _p2_param_24_stdev1sq_limbs[] = {169060907886838UL, 0UL};
static const int_t _p2_param_24_stdev1sq = {{(limb_t *)_p2_param_24_stdev1sq_limbs, 2, 0}};
static const limb_t _p2_param_24_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t _p2_param_24_stdev2sq = {{(limb_t *)_p2_param_24_stdev2sq_limbs, 2, 0}};
static const limb_t _p2_param_24_stdev3sq_limbs[] = {165098542858UL, 0UL};
static const int_t _p2_param_24_stdev3sq = {{(limb_t *)_p2_param_24_stdev3sq_limbs, 2, 0}};
static const limb_t _p2_param_24_stdev4sq_limbs[] = {692473478704487465UL, 0UL};
static const int_t _p2_param_24_stdev4sq = {{(limb_t *)_p2_param_24_stdev4sq_limbs, 2, 0}};
static const limb_t _p2_param_24_inv2_limbs[] = {562949953421594UL};
static const int_t _p2_param_24_inv2 = {{(limb_t *)_p2_param_24_inv2_limbs, 1, 1}};
static const limb_t _p2_param_24_inv4_limbs[] = {281474976710797UL};
static const int_t _p2_param_24_inv4 = {{(limb_t *)_p2_param_24_inv4_limbs, 1, 1}};
static const unsigned int _p2_param_24_n[2] = {16, 16};
static const limb_t _p2_param_24_Bz3sqr_limbs[] = {113676554463109UL, 0UL};
static const int_t _p2_param_24_Bz3sqr = {{(limb_t *)_p2_param_24_Bz3sqr_limbs, 2, 0}};
static const limb_t _p2_param_24_Bz4_limbs[] = {13314398617UL};
static const int_t _p2_param_24_Bz4 = {{(limb_t *)_p2_param_24_Bz4_limbs, 1, 0}};
static const limb_t _p2_param_24_Pmodq_limbs[] = {42568471872UL};
static const int_t _p2_param_24_Pmodq = {{(limb_t *)_p2_param_24_Pmodq_limbs, 1, 1}};
static const limb_t _p2_param_24_l2Bsq0_limbs[] = {11881UL};
static const int_t _p2_param_24_l2Bsq0 = {{(limb_t *)_p2_param_24_l2Bsq0_limbs, 1, 0}};
static const limb_t _p2_param_24_l2Bsq1_limbs[] = {34034726UL};
static const int_t _p2_param_24_l2Bsq1 = {{(limb_t *)_p2_param_24_l2Bsq1_limbs, 1, 0}};
static const limb_t _p2_param_24_Ppmodq_0_limbs[] = {18068112UL};
static const int_t _p2_param_24_Ppmodq_0 = {{(limb_t *)_p2_param_24_Ppmodq_0_limbs, 1, 0}};
static const limb_t _p2_param_24_Ppmodq_1_limbs[] = {13089936UL};
static const int_t _p2_param_24_Ppmodq_1 = {{(limb_t *)_p2_param_24_Ppmodq_1_limbs, 1, 0}};
static const limb_t _p2_param_24_Ppmodq_2_limbs[] = {7661712UL};
static const int_t _p2_param_24_Ppmodq_2 = {{(limb_t *)_p2_param_24_Ppmodq_2_limbs, 1, 0}};
static const int_srcptr _p2_param_24_l2Bsq[] = {_p2_param_24_l2Bsq0, _p2_param_24_l2Bsq1};
static const int_srcptr _p2_param_24_Ppmodq[] = {_p2_param_24_Ppmodq_0, _p2_param_24_Ppmodq_1, _p2_param_24_Ppmodq_2};
static const polyring_t _p2_param_24_ring = {{_p2_param_24_q, 64, 51, 6, moduli_d64, 3, _p2_param_24_Pmodq, _p2_param_24_Ppmodq, _p2_param_24_inv2}};
static const dcompress_params_t _p2_param_24_dcomp = {{ _p2_param_24_q, _p2_param_24_qminus1, _p2_param_24_m, _p2_param_24_mby2, _p2_param_24_gamma, _p2_param_24_gammaby2, _p2_param_24_pow2D, _p2_param_24_pow2Dby2, 17, 0, 25 }};
static const abdlop_params_t _p2_param_24_tbox = {{ _p2_param_24_ring, _p2_param_24_dcomp, 70, 65, 0, 12, 21, _p2_param_24_Bsq, 1, 8, 5, 140, 1, 23, _p2_param_24_scM1, _p2_param_24_stdev1sq, 2, 12, _p2_param_24_scM2, _p2_param_24_stdev2sq}};
static const abdlop_params_t _p2_param_24_quad_eval_ = {{ _p2_param_24_ring, _p2_param_24_dcomp, 70, 65, 9, 3, 21, _p2_param_24_Bsq, 1, 8, 5, 140, 1, 23, _p2_param_24_scM1, _p2_param_24_stdev1sq, 2, 12, _p2_param_24_scM2, _p2_param_24_stdev2sq}};
static const abdlop_params_t _p2_param_24_quad_many_ = {{ _p2_param_24_ring, _p2_param_24_dcomp, 70, 65, 11, 1, 21, _p2_param_24_Bsq, 1, 8, 5, 140, 1, 23, _p2_param_24_scM1, _p2_param_24_stdev1sq, 2, 12, _p2_param_24_scM2, _p2_param_24_stdev2sq}};
static const lnp_quad_eval_params_t _p2_param_24_quad_eval = {{ _p2_param_24_quad_eval_, _p2_param_24_quad_many_, 4}};
static const lnp_tbox_params_t _p2_param_24 = {{ _p2_param_24_tbox, _p2_param_24_quad_eval, 36, _p2_param_24_n, 8, 2, 70, 2, 18, _p2_param_24_scM3, _p2_param_24_stdev3sq, 2, 29, _p2_param_24_scM4, _p2_param_24_stdev4sq, _p2_param_24_Bz3sqr, _p2_param_24_Bz4, &_p2_param_24_l2Bsq[0], _p2_param_24_inv4, 34354UL }};

static const unsigned int p2_param_24_Ps[36] = {16, 17, 18, 19, 20, 21, 22, 23, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67};
static const unsigned int p2_param_24_Es0[16] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const unsigned int p2_param_24_Es1[16] = {24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39};
static const unsigned int *p2_param_24_Es[2] = { p2_param_24_Es0, p2_param_24_Es1, };
static const unsigned int p2_param_24_Es_nrows[2] = {16, 16};

static const limb_t p2_param_24_p_limbs[] = {12289UL};
static const int_t p2_param_24_p = {{(limb_t *)p2_param_24_p_limbs, 1, 0}};
static const limb_t p2_param_24_pinv_limbs[] = {60834692663673UL};
static const int_t p2_param_24_pinv = {{(limb_t *)p2_param_24_pinv_limbs, 1, 0}};
static const unsigned int p2_param_24_s1_indices[68] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67};
static const lin_params_t p2_param_24 = {{ _p2_param_24, 64, p2_param_24_p, p2_param_24_pinv, 1, p2_param_24_s1_indices, 68, NULL, 0,  p2_param_24_Ps, 36, p2_param_24_Es, p2_param_24_Es_nrows, NULL, NULL }};

// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(32,32,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(20,140,2^(40.569955))
// 
// Ring
// degree d = 64
// modulus q = 2251799813685269, log(q) ~ 51.0
// factors q = q1
// 
// Compression
// D = 16
// gamma = 27699892, log(gamma) ~ 24.723377
// 
// Dimensions of secrets
// s1: m1 = 76
// m: l = 0
// s2: m2 = 64
// 
// Size of secrets
// l2(s1) <= alpha = 5836.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 44)
// exact euclidean: yes (dimensions: [16, 16], bounds: [109.0, 5833.9289])
// approximate infinity: yes (psi: 3971.1569, dimension: 8, bound: 14184702.0)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 13002342.4, log(stdev1/1.55) = 23.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 406323.2, log(stdev3/1.55) = 18.0
// stdev4 = 1664299827.2, log(stdev4/1.55) = 30.0
// 
// Repetition rate
// M1 = 2.3216894
// M2 = 2.707079
// M3 = 1.0353619
// M4 = 1.0123151
// total = 6.5873836
// 
// Security
// MSIS dimension: 20
// MSIS root hermite factor: 1.0043787
// MLWE dimension: 32
// MLWE root hermite factor: 1.0043992
// 
// Proof size
// ~ 35.4062500000000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t _p2_param_32_q_limbs[] = {2251799813685269UL};
static const int_t _p2_param_32_q = {{(limb_t *)_p2_param_32_q_limbs, 1, 0}};
static const limb_t _p2_param_32_qminus1_limbs[] = {2251799813685268UL};
static const int_t _p2_param_32_qminus1 = {{(limb_t *)_p2_param_32_qminus1_limbs, 1, 0}};
static const limb_t _p2_param_32_m_limbs[] = {81292729UL};
static const int_t _p2_param_32_m = {{(limb_t *)_p2_param_32_m_limbs, 1, 0}};
static const limb_t _p2_param_32_mby2_limbs[] = {40646364UL};
static const int_t _p2_param_32_mby2 = {{(limb_t *)_p2_param_32_mby2_limbs, 1, 0}};
static const limb_t _p2_param_32_gamma_limbs[] = {27699892UL};
static const int_t _p2_param_32_gamma = {{(limb_t *)_p2_param_32_gamma_limbs, 1, 0}};
static const limb_t _p2_param_32_gammaby2_limbs[] = {13849946UL};
static const int_t _p2_param_32_gammaby2 = {{(limb_t *)_p2_param_32_gammaby2_limbs, 1, 0}};
static const limb_t _p2_param_32_pow2D_limbs[] = {65536UL};
static const int_t _p2_param_32_pow2D = {{(limb_t *)_p2_param_32_pow2D_limbs, 1, 0}};
static const limb_t _p2_param_32_pow2Dby2_limbs[] = {32768UL};
static const int_t _p2_param_32_pow2Dby2 = {{(limb_t *)_p2_param_32_pow2Dby2_limbs, 1, 0}};
static const limb_t _p2_param_32_Bsq_limbs[] = {435881818999706017UL, 0UL};
static const int_t _p2_param_32_Bsq = {{(limb_t *)_p2_param_32_Bsq_limbs, 2, 0}};
static const limb_t _p2_param_32_scM1_limbs[] = {9859465049745963634UL, 5934122506364705697UL, 2UL};
static const int_t _p2_param_32_scM1 = {{(limb_t *)_p2_param_32_scM1_limbs, 3, 0}};
static const limb_t _p2_param_32_scM2_limbs[] = {15002606599518648986UL, 13043305028329312333UL, 2UL};
static const int_t _p2_param_32_scM2 = {{(limb_t *)_p2_param_32_scM2_limbs, 3, 0}};
static const limb_t _p2_param_32_scM3_limbs[] = {6523355532159809564UL, 652312538284507341UL, 1UL};
static const int_t _p2_param_32_scM3 = {{(limb_t *)_p2_param_32_scM3_limbs, 3, 0}};
static const limb_t _p2_param_32_scM4_limbs[] = {8720774424856239694UL, 227173411834295427UL, 1UL};
static const int_t _p2_param_32_scM4 = {{(limb_t *)_p2_param_32_scM4_limbs, 3, 0}};
static const limb_t _p2_param_32_stdev1sq_limbs[] = {169060907886838UL, 0UL};
static const int_t _p2_param_32_stdev1sq = {{(limb_t *)_p2_param_32_stdev1sq_limbs, 2, 0}};
static const limb_t _p2_param_32_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t _p2_param_32_stdev2sq = {{(limb_t *)_p2_param_32_stdev2sq_limbs, 2, 0}};
static const limb_t _p2_param_32_stdev3sq_limbs[] = {165098542858UL, 0UL};
static const int_t _p2_param_32_stdev3sq = {{(limb_t *)_p2_param_32_stdev3sq_limbs, 2, 0}};
static const limb_t _p2_param_32_stdev4sq_limbs[] = {2769893914817949860UL, 0UL};
static const int_t _p2_param_32_stdev4sq = {{(limb_t *)_p2_param_32_stdev4sq_limbs, 2, 0}};
static const limb_t _p2_param_32_inv2_limbs[] = {1125899906842634UL};
static const int_t _p2_param_32_inv2 = {{(limb_t *)_p2_param_32_inv2_limbs, 1, 1}};
static const limb_t _p2_param_32_inv4_limbs[] = {562949953421317UL};
static const int_t _p2_param_32_inv4 = {{(limb_t *)_p2_param_32_inv4_limbs, 1, 1}};
static const unsigned int _p2_param_32_n[2] = {16, 16};
static const limb_t _p2_param_32_Bz3sqr_limbs[] = {113676554463109UL, 0UL};
static const int_t _p2_param_32_Bz3sqr = {{(limb_t *)_p2_param_32_Bz3sqr_limbs, 2, 0}};
static const limb_t _p2_param_32_Bz4_limbs[] = {26628797235UL};
static const int_t _p2_param_32_Bz4 = {{(limb_t *)_p2_param_32_Bz4_limbs, 1, 0}};
static const limb_t _p2_param_32_Pmodq_limbs[] = {281499281731228UL};
static const int_t _p2_param_32_Pmodq = {{(limb_t *)_p2_param_32_Pmodq_limbs, 1, 1}};
static const limb_t _p2_param_32_l2Bsq0_limbs[] = {11881UL};
static const int_t _p2_param_32_l2Bsq0 = {{(limb_t *)_p2_param_32_l2Bsq0_limbs, 1, 0}};
static const limb_t _p2_param_32_l2Bsq1_limbs[] = {34034726UL};
static const int_t _p2_param_32_l2Bsq1 = {{(limb_t *)_p2_param_32_l2Bsq1_limbs, 1, 0}};
static const limb_t _p2_param_32_Ppmodq_0_limbs[] = {562949939929771UL};
static const int_t _p2_param_32_Ppmodq_0 = {{(limb_t *)_p2_param_32_Ppmodq_0_limbs, 1, 1}};
static const limb_t _p2_param_32_Ppmodq_1_limbs[] = {562949944411115UL};
static const int_t _p2_param_32_Ppmodq_1 = {{(limb_t *)_p2_param_32_Ppmodq_1_limbs, 1, 1}};
static const limb_t _p2_param_32_Ppmodq_2_limbs[] = {562949948561771UL};
static const int_t _p2_param_32_Ppmodq_2 = {{(limb_t *)_p2_param_32_Ppmodq_2_limbs, 1, 1}};
static const int_srcptr _p2_param_32_l2Bsq[] = {_p2_param_32_l2Bsq0, _p2_param_32_l2Bsq1};
static const int_srcptr _p2_param_32_Ppmodq[] = {_p2_param_32_Ppmodq_0, _p2_param_32_Ppmodq_1, _p2_param_32_Ppmodq_2};
static const polyring_t _p2_param_32_ring = {{_p2_param_32_q, 64, 52, 6, moduli_d64, 3, _p2_param_32_Pmodq, _p2_param_32_Ppmodq, _p2_param_32_inv2}};
static const dcompress_params_t _p2_param_32_dcomp = {{ _p2_param_32_q, _p2_param_32_qminus1, _p2_param_32_m, _p2_param_32_mby2, _p2_param_32_gamma, _p2_param_32_gammaby2, _p2_param_32_pow2D, _p2_param_32_pow2Dby2, 16, 1, 27 }};
static const abdlop_params_t _p2_param_32_tbox = {{ _p2_param_32_ring, _p2_param_32_dcomp, 78, 64, 0, 12, 20, _p2_param_32_Bsq, 1, 8, 5, 140, 1, 23, _p2_param_32_scM1, _p2_param_32_stdev1sq, 2, 12, _p2_param_32_scM2, _p2_param_32_stdev2sq}};
static const abdlop_params_t _p2_param_32_quad_eval_ = {{ _p2_param_32_ring, _p2_param_32_dcomp, 78, 64, 9, 3, 20, _p2_param_32_Bsq, 1, 8, 5, 140, 1, 23, _p2_param_32_scM1, _p2_param_32_stdev1sq, 2, 12, _p2_param_32_scM2, _p2_param_32_stdev2sq}};
static const abdlop_params_t _p2_param_32_quad_many_ = {{ _p2_param_32_ring, _p2_param_32_dcomp, 78, 64, 11, 1, 20, _p2_param_32_Bsq, 1, 8, 5, 140, 1, 23, _p2_param_32_scM1, _p2_param_32_stdev1sq, 2, 12, _p2_param_32_scM2, _p2_param_32_stdev2sq}};
static const lnp_quad_eval_params_t _p2_param_32_quad_eval = {{ _p2_param_32_quad_eval_, _p2_param_32_quad_many_, 4}};
static const lnp_tbox_params_t _p2_param_32 = {{ _p2_param_32_tbox, _p2_param_32_quad_eval, 44, _p2_param_32_n, 8, 2, 78, 2, 18, _p2_param_32_scM3, _p2_param_32_stdev3sq, 2, 30, _p2_param_32_scM4, _p2_param_32_stdev4sq, _p2_param_32_Bz3sqr, _p2_param_32_Bz4, &_p2_param_32_l2Bsq[0], _p2_param_32_inv4, 36256UL }};

static const unsigned int p2_param_32_Ps[44] = {16, 17, 18, 19, 20, 21, 22, 23, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75};
static const unsigned int p2_param_32_Es0[16] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const unsigned int p2_param_32_Es1[16] = {24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39};
static const unsigned int *p2_param_32_Es[2] = { p2_param_32_Es0, p2_param_32_Es1, };
static const unsigned int p2_param_32_Es_nrows[2] = {16, 16};

static const limb_t p2_param_32_p_limbs[] = {12289UL};
static const int_t p2_param_32_p = {{(limb_t *)p2_param_32_p_limbs, 1, 0}};
static const limb_t p2_param_32_pinv_limbs[] = {449297187985701UL};
static const int_t p2_param_32_pinv = {{(limb_t *)p2_param_32_pinv_limbs, 1, 0}};
static const unsigned int p2_param_32_s1_indices[76] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75};
static const lin_params_t p2_param_32 = {{ _p2_param_32, 64, p2_param_32_p, p2_param_32_pinv, 1, p2_param_32_s1_indices, 76, NULL, 0,  p2_param_32_Ps, 44, p2_param_32_Es, p2_param_32_Es_nrows, NULL, NULL }};

// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(32,32,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(20,152,2^(40.653166))
// 
// Ring
// degree d = 64
// modulus q = 2251799813685269, log(q) ~ 51.0
// factors q = q1
// 
// Compression
// D = 16
// gamma = 27699892, log(gamma) ~ 24.723377
// 
// Dimensions of secrets
// s1: m1 = 88
// m: l = 0
// s2: m2 = 64
// 
// Size of secrets
// l2(s1) <= alpha = 5836.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 56)
// exact euclidean: yes (dimensions: [16, 16], bounds: [109.0, 5833.9289])
// approximate infinity: yes (psi: 3429.6356, dimension: 8, bound: 16424392.0)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 13002342.4, log(stdev1/1.55) = 23.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 406323.2, log(stdev3/1.55) = 18.0
// stdev4 = 1664299827.2, log(stdev4/1.55) = 30.0
// 
// Repetition rate
// M1 = 2.3216894
// M2 = 2.707079
// M3 = 1.0353627
// M4 = 1.0165456
// total = 6.614918
// 
// Security
// MSIS dimension: 20
// MSIS root hermite factor: 1.0043967
// MLWE dimension: 32
// MLWE root hermite factor: 1.0043992
// 
// Proof size
// ~ 37.9375000000000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t _p2_param_44_q_limbs[] = {2251799813685269UL};
static const int_t _p2_param_44_q = {{(limb_t *)_p2_param_44_q_limbs, 1, 0}};
static const limb_t _p2_param_44_qminus1_limbs[] = {2251799813685268UL};
static const int_t _p2_param_44_qminus1 = {{(limb_t *)_p2_param_44_qminus1_limbs, 1, 0}};
static const limb_t _p2_param_44_m_limbs[] = {81292729UL};
static const int_t _p2_param_44_m = {{(limb_t *)_p2_param_44_m_limbs, 1, 0}};
static const limb_t _p2_param_44_mby2_limbs[] = {40646364UL};
static const int_t _p2_param_44_mby2 = {{(limb_t *)_p2_param_44_mby2_limbs, 1, 0}};
static const limb_t _p2_param_44_gamma_limbs[] = {27699892UL};
static const int_t _p2_param_44_gamma = {{(limb_t *)_p2_param_44_gamma_limbs, 1, 0}};
static const limb_t _p2_param_44_gammaby2_limbs[] = {13849946UL};
static const int_t _p2_param_44_gammaby2 = {{(limb_t *)_p2_param_44_gammaby2_limbs, 1, 0}};
static const limb_t _p2_param_44_pow2D_limbs[] = {65536UL};
static const int_t _p2_param_44_pow2D = {{(limb_t *)_p2_param_44_pow2D_limbs, 1, 0}};
static const limb_t _p2_param_44_pow2Dby2_limbs[] = {32768UL};
static const int_t _p2_param_44_pow2Dby2 = {{(limb_t *)_p2_param_44_pow2Dby2_limbs, 1, 0}};
static const limb_t _p2_param_44_Bsq_limbs[] = {435881818999706017UL, 0UL};
static const int_t _p2_param_44_Bsq = {{(limb_t *)_p2_param_44_Bsq_limbs, 2, 0}};
static const limb_t _p2_param_44_scM1_limbs[] = {9859465049745963634UL, 5934122506364705697UL, 2UL};
static const int_t _p2_param_44_scM1 = {{(limb_t *)_p2_param_44_scM1_limbs, 3, 0}};
static const limb_t _p2_param_44_scM2_limbs[] = {15002606599518648986UL, 13043305028329312333UL, 2UL};
static const int_t _p2_param_44_scM2 = {{(limb_t *)_p2_param_44_scM2_limbs, 3, 0}};
static const limb_t _p2_param_44_scM3_limbs[] = {3431148282218434871UL, 652327508566157883UL, 1UL};
static const int_t _p2_param_44_scM3 = {{(limb_t *)_p2_param_44_scM3_limbs, 3, 0}};
static const limb_t _p2_param_44_scM4_limbs[] = {2954587238368643457UL, 305213264234897099UL, 1UL};
static const int_t _p2_param_44_scM4 = {{(limb_t *)_p2_param_44_scM4_limbs, 3, 0}};
static const limb_t _p2_param_44_stdev1sq_limbs[] = {169060907886838UL, 0UL};
static const int_t _p2_param_44_stdev1sq = {{(limb_t *)_p2_param_44_stdev1sq_limbs, 2, 0}};
static const limb_t _p2_param_44_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t _p2_param_44_stdev2sq = {{(limb_t *)_p2_param_44_stdev2sq_limbs, 2, 0}};
static const limb_t _p2_param_44_stdev3sq_limbs[] = {165098542858UL, 0UL};
static const int_t _p2_param_44_stdev3sq = {{(limb_t *)_p2_param_44_stdev3sq_limbs, 2, 0}};
static const limb_t _p2_param_44_stdev4sq_limbs[] = {2769893914817949860UL, 0UL};
static const int_t _p2_param_44_stdev4sq = {{(limb_t *)_p2_param_44_stdev4sq_limbs, 2, 0}};
static const limb_t _p2_param_44_inv2_limbs[] = {1125899906842634UL};
static const int_t _p2_param_44_inv2 = {{(limb_t *)_p2_param_44_inv2_limbs, 1, 1}};
static const limb_t _p2_param_44_inv4_limbs[] = {562949953421317UL};
static const int_t _p2_param_44_inv4 = {{(limb_t *)_p2_param_44_inv4_limbs, 1, 1}};
static const unsigned int _p2_param_44_n[2] = {16, 16};
static const limb_t _p2_param_44_Bz3sqr_limbs[] = {113676554463109UL, 0UL};
static const int_t _p2_param_44_Bz3sqr = {{(limb_t *)_p2_param_44_Bz3sqr_limbs, 2, 0}};
static const limb_t _p2_param_44_Bz4_limbs[] = {26628797235UL};
static const int_t _p2_param_44_Bz4 = {{(limb_t *)_p2_param_44_Bz4_limbs, 1, 0}};
static const limb_t _p2_param_44_Pmodq_limbs[] = {281499281731228UL};
static const int_t _p2_param_44_Pmodq = {{(limb_t *)_p2_param_44_Pmodq_limbs, 1, 1}};
static const limb_t _p2_param_44_l2Bsq0_limbs[] = {11881UL};
static const int_t _p2_param_44_l2Bsq0 = {{(limb_t *)_p2_param_44_l2Bsq0_limbs, 1, 0}};
static const limb_t _p2_param_44_l2Bsq1_limbs[] = {34034726UL};
static const int_t _p2_param_44_l2Bsq1 = {{(limb_t *)_p2_param_44_l2Bsq1_limbs, 1, 0}};
static const limb_t _p2_param_44_Ppmodq_0_limbs[] = {562949939929771UL};
static const int_t _p2_param_44_Ppmodq_0 = {{(limb_t *)_p2_param_44_Ppmodq_0_limbs, 1, 1}};
static const limb_t _p2_param_44_Ppmodq_1_limbs[] = {562949944411115UL};
static const int_t _p2_param_44_Ppmodq_1 = {{(limb_t *)_p2_param_44_Ppmodq_1_limbs, 1, 1}};
static const limb_t _p2_param_44_Ppmodq_2_limbs[] = {562949948561771UL};
static const int_t _p2_param_44_Ppmodq_2 = {{(limb_t *)_p2_param_44_Ppmodq_2_limbs, 1, 1}};
static const int_srcptr _p2_param_44_l2Bsq[] = {_p2_param_44_l2Bsq0, _p2_param_44_l2Bsq1};
static const int_srcptr _p2_param_44_Ppmodq[] = {_p2_param_44_Ppmodq_0, _p2_param_44_Ppmodq_1, _p2_param_44_Ppmodq_2};
static const polyring_t _p2_param_44_ring = {{_p2_param_44_q, 64, 52, 6, moduli_d64, 3, _p2_param_44_Pmodq, _p2_param_44_Ppmodq, _p2_param_44_inv2}};
static const dcompress_params_t _p2_param_44_dcomp = {{ _p2_param_44_q, _p2_param_44_qminus1, _p2_param_44_m, _p2_param_44_mby2, _p2_param_44_gamma, _p2_param_44_gammaby2, _p2_param_44_pow2D, _p2_param_44_pow2Dby2, 16, 1, 27 }};
static const abdlop_params_t _p2_param_44_tbox = {{ _p2_param_44_ring, _p2_param_44_dcomp, 90, 64, 0, 12, 20, _p2_param_44_Bsq, 1, 8, 5, 140, 1, 23, _p2_param_44_scM1, _p2_param_44_stdev1sq, 2, 12, _p2_param_44_scM2, _p2_param_44_stdev2sq}};
static const abdlop_params_t _p2_param_44_quad_eval_ = {{ _p2_param_44_ring, _p2_param_44_dcomp, 90, 64, 9, 3, 20, _p2_param_44_Bsq, 1, 8, 5, 140, 1, 23, _p2_param_44_scM1, _p2_param_44_stdev1sq, 2, 12, _p2_param_44_scM2, _p2_param_44_stdev2sq}};
static const abdlop_params_t _p2_param_44_quad_many_ = {{ _p2_param_44_ring, _p2_param_44_dcomp, 90, 64, 11, 1, 20, _p2_param_44_Bsq, 1, 8, 5, 140, 1, 23, _p2_param_44_scM1, _p2_param_44_stdev1sq, 2, 12, _p2_param_44_scM2, _p2_param_44_stdev2sq}};
static const lnp_quad_eval_params_t _p2_param_44_quad_eval = {{ _p2_param_44_quad_eval_, _p2_param_44_quad_many_, 4}};
static const lnp_tbox_params_t _p2_param_44 = {{ _p2_param_44_tbox, _p2_param_44_quad_eval, 56, _p2_param_44_n, 8, 2, 90, 2, 18, _p2_param_44_scM3, _p2_param_44_stdev3sq, 2, 30, _p2_param_44_scM4, _p2_param_44_stdev4sq, _p2_param_44_Bz3sqr, _p2_param_44_Bz4, &_p2_param_44_l2Bsq[0], _p2_param_44_inv4, 38848UL }};

static const unsigned int p2_param_44_Ps[56] = {16, 17, 18, 19, 20, 21, 22, 23, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87};
static const unsigned int p2_param_44_Es0[16] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const unsigned int p2_param_44_Es1[16] = {24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39};
static const unsigned int *p2_param_44_Es[2] = { p2_param_44_Es0, p2_param_44_Es1, };
static const unsigned int p2_param_44_Es_nrows[2] = {16, 16};

static const limb_t p2_param_44_p_limbs[] = {12289UL};
static const int_t p2_param_44_p = {{(limb_t *)p2_param_44_p_limbs, 1, 0}};
static const limb_t p2_param_44_pinv_limbs[] = {449297187985701UL};
static const int_t p2_param_44_pinv = {{(limb_t *)p2_param_44_pinv_limbs, 1, 0}};
static const unsigned int p2_param_44_s1_indices[88] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87};
static const lin_params_t p2_param_44 = {{ _p2_param_44, 64, p2_param_44_p, p2_param_44_pinv, 1, p2_param_44_s1_indices, 88, NULL, 0,  p2_param_44_Ps, 56, p2_param_44_Es, p2_param_44_Es_nrows, NULL, NULL }};

// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(32,32,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(20,168,2^(40.659048))
// 
// Ring
// degree d = 64
// modulus q = 2251799813685269, log(q) ~ 51.0
// factors q = q1
// 
// Compression
// D = 15
// gamma = 13849946, log(gamma) ~ 23.723377
// 
// Dimensions of secrets
// s1: m1 = 104
// m: l = 0
// s2: m2 = 64
// 
// Size of secrets
// l2(s1) <= alpha = 5836.0
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: yes (dimension: 72)
// exact euclidean: yes (dimensions: [16, 16], bounds: [109.0, 5833.9289])
// approximate infinity: yes (psi: 2901.9993, dimension: 8, bound: 19410645.0)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 13002342.4, log(stdev1/1.55) = 23.0
// stdev2 = 6348.8, log(stdev2/1.55) = 12.0
// stdev3 = 406323.2, log(stdev3/1.55) = 18.0
// stdev4 = 1664299827.2, log(stdev4/1.55) = 30.0
// 
// Repetition rate
// M1 = 2.3216894
// M2 = 2.707079
// M3 = 1.0353638
// M4 = 1.0231848
// total = 6.6581276
// 
// Security
// MSIS dimension: 20
// MSIS root hermite factor: 1.004398
// MLWE dimension: 32
// MLWE root hermite factor: 1.0043992
// 
// Proof size
// ~ 41.4687500000000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633]
// bit length of products: [49, 99, 149]
// inverses: [1, -162099428551732, 296975494591860]

#include "lazer.h"
static const limb_t _p2_param_60_q_limbs[] = {2251799813685269UL};
static const int_t _p2_param_60_q = {{(limb_t *)_p2_param_60_q_limbs, 1, 0}};
static const limb_t _p2_param_60_qminus1_limbs[] = {2251799813685268UL};
static const int_t _p2_param_60_qminus1 = {{(limb_t *)_p2_param_60_qminus1_limbs, 1, 0}};
static const limb_t _p2_param_60_m_limbs[] = {162585458UL};
static const int_t _p2_param_60_m = {{(limb_t *)_p2_param_60_m_limbs, 1, 0}};
static const limb_t _p2_param_60_mby2_limbs[] = {81292729UL};
static const int_t _p2_param_60_mby2 = {{(limb_t *)_p2_param_60_mby2_limbs, 1, 0}};
static const limb_t _p2_param_60_gamma_limbs[] = {13849946UL};
static const int_t _p2_param_60_gamma = {{(limb_t *)_p2_param_60_gamma_limbs, 1, 0}};
static const limb_t _p2_param_60_gammaby2_limbs[] = {6924973UL};
static const int_t _p2_param_60_gammaby2 = {{(limb_t *)_p2_param_60_gammaby2_limbs, 1, 0}};
static const limb_t _p2_param_60_pow2D_limbs[] = {32768UL};
static const int_t _p2_param_60_pow2D = {{(limb_t *)_p2_param_60_pow2D_limbs, 1, 0}};
static const limb_t _p2_param_60_pow2Dby2_limbs[] = {16384UL};
static const int_t _p2_param_60_pow2Dby2 = {{(limb_t *)_p2_param_60_pow2Dby2_limbs, 1, 0}};
static const limb_t _p2_param_60_Bsq_limbs[] = {109160225798025947UL, 0UL};
static const int_t _p2_param_60_Bsq = {{(limb_t *)_p2_param_60_Bsq_limbs, 2, 0}};
static const limb_t _p2_param_60_scM1_limbs[] = {9859465049745963634UL, 5934122506364705697UL, 2UL};
static const int_t _p2_param_60_scM1 = {{(limb_t *)_p2_param_60_scM1_limbs, 3, 0}};
static const limb_t _p2_param_60_scM2_limbs[] = {15002606599518648986UL, 13043305028329312333UL, 2UL};
static const int_t _p2_param_60_scM2 = {{(limb_t *)_p2_param_60_scM2_limbs, 3, 0}};
static const limb_t _p2_param_60_scM3_limbs[] = {1552990360427936505UL, 652347468959944911UL, 1UL};
static const int_t _p2_param_60_scM3 = {{(limb_t *)_p2_param_60_scM3_limbs, 3, 0}};
static const limb_t _p2_param_60_scM4_limbs[] = {6850820566316904179UL, 427683961045428066UL, 1UL};
static const int_t _p2_param_60_scM4 = {{(limb_t *)_p2_param_60_scM4_limbs, 3, 0}};
static const limb_t _p2_param_60_stdev1sq_limbs[] = {169060907886838UL, 0UL};
static const int_t _p2_param_60_stdev1sq = {{(limb_t *)_p2_param_60_stdev1sq_limbs, 2, 0}};
static const limb_t _p2_param_60_stdev2sq_limbs[] = {40307261UL, 0UL};
static const int_t _p2_param_60_stdev2sq = {{(limb_t *)_p2_param_60_stdev2sq_limbs, 2, 0}};
static const limb_t _p2_param_60_stdev3sq_limbs[] = {165098542858UL, 0UL};
static const int_t _p2_param_60_stdev3sq = {{(limb_t *)_p2_param_60_stdev3sq_limbs, 2, 0}};
static const limb_t _p2_param_60_stdev4sq_limbs[] = {2769893914817949860UL, 0UL};
static const int_t _p2_param_60_stdev4sq = {{(limb_t *)_p2_param_60_stdev4sq_limbs, 2, 0}};
static const limb_t _p2_param_60_inv2_limbs[] = {1125899906842634UL};
static const int_t _p2_param_60_inv2 = {{(limb_t *)_p2_param_60_inv2_limbs, 1, 1}};
static const limb_t _p2_param_60_inv4_limbs[] = {562949953421317UL};
static const int_t _p2_param_60_inv4 = {{(limb_t *)_p2_param_60_inv4_limbs, 1, 1}};
static const unsigned int _p2_param_60_n[2] = {16, 16};
static const limb_t _p2_param_60_Bz3sqr_limbs[] = {113676554463109UL, 0UL};
static const int_t _p2_param_60_Bz3sqr = {{(limb_t *)_p2_param_60_Bz3sqr_limbs, 2, 0}};
static const limb_t _p2_param_60_Bz4_limbs[] = {26628797235UL};
static const int_t _p2_param_60_Bz4 = {{(limb_t *)_p2_param_60_Bz4_limbs, 1, 0}};
static const limb_t _p2_param_60_Pmodq_limbs[] = {281499281731228UL};
static const int_t _p2_param_60_Pmodq = {{(limb_t *)_p2_param_60_Pmodq_limbs, 1, 1}};
static const limb_t _p2_param_60_l2Bsq0_limbs[] = {11881UL};
static const int_t _p2_param_60_l2Bsq0 = {{(limb_t *)_p2_param_60_l2Bsq0_limbs, 1, 0}};
static const limb_t _p2_param_60_l2Bsq1_limbs[] = {34034726UL};
static const int_t _p2_param_60_l2Bsq1 = {{(limb_t *)_p2_param_60_l2Bsq1_limbs, 1, 0}};
static const limb_t _p2_param_60_Ppmodq_0_limbs[] = {562949939929771UL};
static const int_t _p2_param_60_Ppmodq_0 = {{(limb_t *)_p2_param_60_Ppmodq_0_limbs, 1, 1}};
static const limb_t _p2_param_60_Ppmodq_1_limbs[] = {562949944411115UL};
static const int_t _p2_param_60_Ppmodq_1 = {{(limb_t *)_p2_param_60_Ppmodq_1_limbs, 1, 1}};
static const limb_t _p2_param_60_Ppmodq_2_limbs[] = {562949948561771UL};
static const int_t _p2_param_60_Ppmodq_2 = {{(limb_t *)_p2_param_60_Ppmodq_2_limbs, 1, 1}};
static const int_srcptr _p2_param_60_l2Bsq[] = {_p2_param_60_l2Bsq0, _p2_param_60_l2Bsq1};
static const int_srcptr _p2_param_60_Ppmodq[] = {_p2_param_60_Ppmodq_0, _p2_param_60_Ppmodq_1, _p2_param_60_Ppmodq_2};
static const polyring_t _p2_param_60_ring = {{_p2_param_60_q, 64, 52, 6, moduli_d64, 3, _p2_param_60_Pmodq, _p2_param_60_Ppmodq, _p2_param_60_inv2}};
static const dcompress_params_t _p2_param_60_dcomp = {{ _p2_param_60_q, _p2_param_60_qminus1, _p2_param_60_m, _p2_param_60_mby2, _p2_param_60_gamma, _p2_param_60_gammaby2, _p2_param_60_pow2D, _p2_param_60_pow2Dby2, 15, 0, 28 }};
static const abdlop_params_t _p2_param_60_tbox = {{ _p2_param_60_ring, _p2_param_60_dcomp, 106, 64, 0, 12, 20, _p2_param_60_Bsq, 1, 8, 5, 140, 1, 23, _p2_param_60_scM1, _p2_param_60_stdev1sq, 2, 12, _p2_param_60_scM2, _p2_param_60_stdev2sq}};
static const abdlop_params_t _p2_param_60_quad_eval_ = {{ _p2_param_60_ring, _p2_param_60_dcomp, 106, 64, 9, 3, 20, _p2_param_60_Bsq, 1, 8, 5, 140, 1, 23, _p2_param_60_scM1, _p2_param_60_stdev1sq, 2, 12, _p2_param_60_scM2, _p2_param_60_stdev2sq}};
static const abdlop_params_t _p2_param_60_quad_many_ = {{ _p2_param_60_ring, _p2_param_60_dcomp, 106, 64, 11, 1, 20, _p2_param_60_Bsq, 1, 8, 5, 140, 1, 23, _p2_param_60_scM1, _p2_param_60_stdev1sq, 2, 12, _p2_param_60_scM2, _p2_param_60_stdev2sq}};
static const lnp_quad_eval_params_t _p2_param_60_quad_eval = {{ _p2_param_60_quad_eval_, _p2_param_60_quad_many_, 4}};
static const lnp_tbox_params_t _p2_param_60 = {{ _p2_param_60_tbox, _p2_param_60_quad_eval, 72, _p2_param_60_n, 8, 2, 106, 2, 18, _p2_param_60_scM3, _p2_param_60_stdev3sq, 2, 30, _p2_param_60_scM4, _p2_param_60_stdev4sq, _p2_param_60_Bz3sqr, _p2_param_60_Bz4, &_p2_param_60_l2Bsq[0], _p2_param_60_inv4, 42464UL }};

static const unsigned int p2_param_60_Ps[72] = {16, 17, 18, 19, 20, 21, 22, 23, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103};
static const unsigned int p2_param_60_Es0[16] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const unsigned int p2_param_60_Es1[16] = {24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39};
static const unsigned int *p2_param_60_Es[2] = { p2_param_60_Es0, p2_param_60_Es1, };
static const unsigned int p2_param_60_Es_nrows[2] = {16, 16};

static const limb_t p2_param_60_p_limbs[] = {12289UL};
static const int_t p2_param_60_p = {{(limb_t *)p2_param_60_p_limbs, 1, 0}};
static const limb_t p2_param_60_pinv_limbs[] = {449297187985701UL};
static const int_t p2_param_60_pinv = {{(limb_t *)p2_param_60_pinv_limbs, 1, 0}};
static const unsigned int p2_param_60_s1_indices[104] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103};
static const lin_params_t p2_param_60 = {{ _p2_param_60, 64, p2_param_60_p, p2_param_60_pinv, 1, p2_param_60_s1_indices, 104, NULL, 0,  p2_param_60_Ps, 72, p2_param_60_Es, p2_param_60_Es_nrows, NULL, NULL }};

